const ADD_TASK = 'task/ADD_TASK';
const UPDATE_TASK = 'task/UPDATE_TASK';
const DELETE_TASK = 'task/DELETE_TASK';
const GET_TASK = 'task/GET_TASK';
const FETCH_TASKS_STRAPI = 'task/FETCH_TASKS_STRAPI';

export default {
  ADD_TASK,
  DELETE_TASK,
  GET_TASK,
  UPDATE_TASK,
  FETCH_TASKS_STRAPI,
};
